### ISSUE TITLE
Don't stop mhh.exe when occur some error

### ISSUE THREAD

**Issue by ravpacheco** [takenet/messaginghub-client-csharp#3]
Hello guys, I'm experimenting some problem and I would suggest some enhancement.

When I was coding my bot I make a typo mistake on application.json and then mhh.exe stopped and I couldn't see where was the problem.

For instance:

I created a _PlainText**XPTO**MessageReceiver.cs_

and setted my application.json as 

"messageReceivers": [
    {
      "type": "**PlainTextMessageReceiver**",
      "mediaType": "text/plain"
    },
....

My suggestion is not close mhh.exe on this cases and just print the message.

**Comment by andrebires** [comment]
This is current possible by putting the argument `--pause` into the *Project properties > Debug > Command line arguments*.

**Comment by ravpacheco** [comment]
Great \o/

It's work.
Tks @andrebires
