### ISSUE TITLE
Log messages received also when using Navigation

### ISSUE THREAD

**Issue by ravpacheco** [takenet/messaginghub-client-csharp#5]
Hello guys,

I'm using the **Navigation** feature as proposed [here](https://github.com/takenet/messaginghub-client-csharp/blob/master/src/Samples/Navigation/application.json) and I noted that all messages received and managed automatically are not logged.

Maybe log also this messages could be very nice to help debug process.

**Comment by brenoqueiroz** [comment]
All the envelopes sent/received by your connection are logged using Trace, so to see them when debugging you can set to log to console all the trace.

Trace.Listeners.Add(new TextWriterTraceListener(Console.Out));
The best place to put this code is in the Startup.cs
