### ISSUE TITLE
Problem using inadequated mmh tool version

### ISSUE THREAD

**Issue by ravpacheco** [takenet/messaginghub-client-csharp#6]
Is interesting to force the correct mmh tool when user install or update the MessagingHub.Client.

If for some reason the user install one version of Lime protocol (or other commum library) and use a mmh tool that have another version of Lime some problems can occur.

For example: https://github.com/takenet/lime-csharp/issues/3

**Comment by brenoqueiroz** [comment]
This tool was add by the template package, we moved this feature to the host package. Now the mhh tool will be based on the host package.
